server:
  port: 8081

spring:
  application:
    name: weather-data-server
  redis:
        host: 192.168.93.88
        port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/